; Autogenerated with DRAKON Editor 1.23
; AutoHotkey_L beta v1.7 code generator used


;Header starts here.
gosub, Free_MsgBox
return ;This "return" is here to prevent unintended execution of code.
;Header ends here.


;Diagram "Free_MsgBox".
return ;This "return" is here to protect Free type diagram from unintended execution.
Free_MsgBox:
{} ;This empty block is there to prevent error caused by interaction of label and other code (for example function definition).
    ; item 4
    msgbox, This script is created with Free type diagram.
return


