/* Autogenerated with DRAKON Editor 1.32 */
#include "test.h"


static void tet(void);







static void tet(void) {
    
    int i=0;
    
    if (1==1) {
        
        i=1;
    }
}

void tet2(void) {
    
    int i=0;
    
    if (1==1) {
        
        i=1;
    }
}



