#!/usr/bin/env bash

tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/1 (Hello, world).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/2 (header and footer).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/3 Free type (Hello, world).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/4 (hotkey diagrams).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/5 (sum of parameters).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/6 (if).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/7 (Switch).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/8 (Switch).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/9 (Do-check loop).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/10 (Check-Do loop).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/11 (Do-Check-Do (hybrid) loop).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/12 (For loop).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/13 (For loop without loop icons).drn"
tclsh8.6 ../drakon_gen.tcl -in "../docs/AutoHotkey/Diagrams from Documentation/14 (Simplified For loop).drn"

tclsh8.6 ../drakon_gen.tcl -in "../examples/AutoHotkey/Fibonacci sequence.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/AutoHotkey/Get position and color of pixel.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/automaton/C/automaton-c.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/automaton/C#/automaton-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/automaton/Erlang/code_door.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/automaton/Erlang/lexer.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/automaton/Lua/automaton-lua.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/C/c_demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/C#/Demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/C#/ReverseStringComparer.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/C#/Sorter.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/C++/cpp_demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/C++/StringList.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/D/test.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Erlang/erldemo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Java/Demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Java/ReverseStringComparer.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Java/Sorter.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Javascript/Demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Lua/lua_demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Processing.org/south_norway/Displacement.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Processing.org/south_norway/Sky.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Python/python_demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/QtC++/qt_cpp.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/globals.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/indexed.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/indexed2.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/m2m.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/ownarrow.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/ownpaw.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/peerarrow.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/peerpaw.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C/simple.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/01-simple-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/02-index-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/03-index2-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/04-peer-arrow-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/05-own-arrow-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/06-peer-paw-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/07-own-paw-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/08-m2m-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/09-inherit-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/10-inherit2-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/C#/11-oop-cs.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/01-simple-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/02-index-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/03-index2-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/04-peer-arrow-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/05-own-arrow-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/06-peer-paw-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/07-own-paw-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/08-m2m-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/09-inherit-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/structure/Tcl/10-inherit2-tcl.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Tcl/tcl_demo.drn"
tclsh8.6 ../drakon_gen.tcl -in "../examples/Verilog/verilog_example.drn"
