/* Autogenerated with DRAKON Editor 1.27 */
#ifndef CPP_DEMO_H12128
#define CPP_DEMO_H12128

#include "StringList.h"








int main(
    int argc,
    char** argv
);

class SimpleComparer : public IStringComparer
{


public:
    virtual int Compare(
        const std::string* left,
        const std::string* right
    ) const;

};

#endif

