% Autogenerated with DRAKON Editor 1.21

-module(erlcomma).
-export([main/1]).

main(N) ->
    % item 60001
    if N =:= 1 -> 
        % item 21
        io:format("hi~n"),
        % item 17
        io:format("hi~n"),
        % item 26
        io:format("hi~n")
    ; true ->
        % item 60002
        if N =:= 2 -> 
            % item 22
            % item 18
            io:format("hi~n"),
            % item 25
            io:format("hi~n")
        ; true ->
            % item 60003
            if N =:= 3 -> 
                % item 19
                io:format("hi~n"),
                % item 24
                io:format("hi~n")
            ; true ->
                % item 27
                % item 20
                io:format("hi~n")
            end
        end
    end,
    % item 290001
    if N =:= 1 -> 
        % item 43
        io:format("hi~n"),
        % item 39
        io:format("hi~n")
    ; true ->
        % item 290002
        if N =:= 2 -> 
            % item 44
            % item 40
            io:format("hi~n")
        ; true ->
            % item 290003
            if N =:= 3 -> 
                % item 41
                io:format("hi~n")
            ; true ->
                []
            end
        end
    end,
    % item 15
    N
.


