# Autogenerated with DRAKON Editor 1.5

proc dummy { collection } {
    set _next_item_ 25
    while { 1 } {
        if {$_next_item_ == 25} {
            if {[ llength $collection ] == 0} {
                #item 26
                puts "empty"
            } else {
                #item 23
                puts "-----------------"
            }
    
        #item 24
            puts "exiting..."
            return {}
        }
    
    }
}

proc print_list { collection } {
    set _next_item_ 11
    while { 1 } {
        if {$_next_item_ == 11} {
            if {[ llength $collection ] == 0} {
                #item 12
                puts "empty"
            } else {
                #item 9
                puts "-----------------"
            }
    
        #item 60001
            set _col6 $collection
            set _len6 [ llength $_col6 ]
            set _ind6 0
            set _next_item_ 60002
        }
    
        if {$_next_item_ == 60002} {
            if {$_ind6 < $_len6} {
                #item 60004
                set item [ lindex $_col6 $_ind6 ]
                #item 7
                puts $item
                #item 60003
                incr _ind6
                set _next_item_ 60002
                continue
            } else {
                #item 10
                puts ""
                return {}
            }
        }
    
    }
}

print_list {}
print_list { one two three }
