this
is text before

# Autogenerated with DRAKON Editor 1.5

proc fun1 { } {

}

proc fun10 { } {
    set _sw_123 select
    if { $_sw_123 == case1 } {
        return ""
    } elseif { $_sw_123 == case2 } {
        return ""
    } else {
        error "Not expected: $_sw_123"
    }
}

proc fun11 { } {
    set _sw_132 select
    if { $_sw_132 == case1 } {
        #item 137
        action1
        return ""
    } elseif { $_sw_132 == case2 } {
        #item 138
        action2
        return ""
    } else {
        error "Not expected: $_sw_132"
    }
}

proc fun2 { one two three } {

}

proc fun3 { } {
    foo
    #item 22
    bar
    return ""
}

proc fun4 { very good } {
    foo1
    #item 36
    foo2
    #item 37
    foo3
    return ""
}

proc fun5 { } {
    set _next_item_ 41
    while { 1 } {
        switch $_next_item_ {
            41 {
                if { first question } {
                    set _next_item_ 42
                } else {
                    set _next_item_ 43
                }
            }
            42 {
                aaa
                return ""
            }
            43 {
                if { second question } {
                    #item 65
                    bbb
                    return ""
                } else {
                    set _next_item_ 42
                }
            }
        }
    }
}

proc fun6 { } {
    set _next_item_ 62-1
    while { 1 } {
        switch $_next_item_ {
            60-2 {
                if { $i < 10 } {
                    #item 60-3
                    incr i
                    set _next_item_ 60-2
                } else {
                    return ""
                }
            }
            62-1 {
                set j 0
                set _next_item_ 62-2
            }
            62-2 {
                if { $j < 10 } {
                    #item 63
                    bar
                    #item 62-3
                    incr j
                    set _next_item_ 62-2
                } else {
                    #item 60-1
                    set i 0
                    set _next_item_ 60-2
                }
            }
        }
    }
}

proc fun7 { } {
    set _next_item_ 78-1
    while { 1 } {
        switch $_next_item_ {
            78-1 {
                for set i 0
                set _next_item_ 78-2
            }
            78-2 {
                if { $i < 10 } {
                    #item 80-1
                    for set j 0
                    set _next_item_ 80-2
                } else {
                    return ""
                }
            }
            80-2 {
                if { $j < 10 } {
                    #item 80-3
                    incr j
                    set _next_item_ 80-2
                } else {
                    #item 78-3
                    incr i
                    set _next_item_ 78-2
                }
            }
        }
    }
}

proc fun8 { } {
    set _next_item_ 95-1
    while { 1 } {
        switch $_next_item_ {
            95-1 {
                for set i 0
                set _next_item_ 95-2
            }
            95-2 {
                if { $i < 10 } {
                    #item 97-1
                    for set j 0
                    set _next_item_ 97-2
                } else {
                    return ""
                }
            }
            97-2 {
                if { $j < 10 } {
                    #item 98
                    bar
                    #item 97-3
                    incr j
                    set _next_item_ 97-2
                } else {
                    #item 95-3
                    incr i
                    set _next_item_ 95-2
                }
            }
        }
    }
}

proc fun9 { } {
    set _next_item_ 112-1
    while { 1 } {
        switch $_next_item_ {
            112-1 {
                for set i 0
                set _next_item_ 112-2
            }
            112-2 {
                if { $i < 10 } {
                    #item 114-1
                    for set j 0
                    set _next_item_ 114-2
                } else {
                    return ""
                }
            }
            114-2 {
                if { $j < 10 } {
                    set _next_item_ 116
                } else {
                    #item 112-3
                    incr i
                    set _next_item_ 112-2
                }
            }
            116 {
                if { question } {
                    return ""
                } else {
                    #item 114-3
                    incr j
                    set _next_item_ 114-2
                }
            }
        }
    }
}

this is text
after
